# Hexo Configuration

## Docs: https://hexo.io/docs/configuration.html

## Source: https://github.com/hexojs/hexo/



# Site
# 网站标题
title: 沂水博客   
# 网站子标题
subtitle: 编程和心历记录   
# 网站描述
description: 记录编程点滴，写点生活中的酸甜
# 网站作者
author:  沂水
# 网站使用的语言  
language: zh-Hans   
# 网站时区。Hexo 预设使用您电脑的时区。   
timezone: Asia/Shanghai         

# URL
url: http://linyishui.top
root: /
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
#不需要渲染的文件夹或文件夹,放在[]中
# 这两个文件是百度和google的站长验证文件，不能渲染，否则会改变内容，不能验证过
skip_render: [baidu_verify_R9MZjdMkXT.html, google0f8fac7da2b48ef8.html, README.md, 模板.md]

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true              
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
index_generator:
  per_page: 5
archive_generator:
  per_page: 30
  yearly: true
  monthly: true
tag_generator:
  per_page: 20

pagination_dir: page

# Extensions
theme: next
plugins: 
baidusitemap: 
  path: baidusitemap.xml

baidu_url_submit:
  count: 100 # 提交最新的一个链接
  host: linyishui.top # 在百度站长平台中注册的域名
  token: Lp5IRUBJLs5q9KpJ # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt # 文本文档的地址， 新链接会保存在此文本文档里

# Deployment
deploy:
- type: git
  repo:
        github: git@github.com:LAILAIWA/LAILAIWA.github.io.git,master
        coding: git@git.coding.net:linyishui/linyishui.git,master
- type: baidu_url_submitter
  message: Site update at {{ now("YYYY-MM-DD HH:mm:ss") }}

# 头像
avatar: https://pic-1258215793.cos.ap-shanghai.myqcloud.com/cover/riho_yoshioka1.jpg

# 动态妹子
live2d:
  enable: true
  scriptFrom: local
  tagMode: true
  model:
    use: live2d-widget-model-shizuku
  display:
    position: left
    width: 100
    height: 200
  mobile:
    show: false


