menu:
  home: / || home #首页
  categories: /categories/ || th #分类
  archives: /archives/ || archive #归档
  tags: /tags/ || tags #标签
  about: /about/ || user #关于
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat

# Content
excerpt_link: 阅读全文    # 设置查看全文的按钮显示文本
fancybox: true           # 是否开启弹出层效果

# Sidebar
sidebar: right    # 侧边栏展示的方向
widgets:          # 侧边栏添加的组件配置
- category        # 显示分类
- tag             # 显示标签
- tagcloud        # 显示标签云
- archive         # 显示归档
- recent_posts    # 显示最近发布

# Miscellaneous
google_analytics:    # 谷歌统计的ID配置，如果你没有用到，可以为空
favicon: /favicon.png                # 网站图标路径
twitter:                             # twitter配置
google_plus:                         # google plus 配置
fb_admins:                           # facebook 配置
fb_app_id:

